[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "node bot.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
maxRestartsPerHour = 10

[env]
NODE_ENV = "production"
PORT = "3000"

[routes]
"/" = "bot.js"

[runtime]
nodeVersion = "20.x" 